-- ============================================================================
-- 02_import_normalized.sql - Import Normalized Data
-- ============================================================================
-- Auto-generated by scripts/transform-csvs.js
-- Do not edit manually - run `npm run seed:transform` to regenerate
-- ============================================================================

DO $$
DECLARE
  shared_household_id UUID;
  user1_id UUID;
  imported_count INTEGER;
BEGIN
  RAISE NOTICE '========================================';
  RAISE NOTICE '[4/5] Importing normalized data...';
  RAISE NOTICE '========================================';

  -- Get IDs
  SELECT id INTO shared_household_id FROM public.households LIMIT 1;
  SELECT id INTO user1_id FROM public.users WHERE email = 'user1@example.com';

  -- ============================================================================
  -- Import Budget Allocations
  -- ============================================================================
  RAISE NOTICE '  Importing budget allocations...';

  -- Budget allocation INSERT statements generated from CSV
  INSERT INTO public.budget_allocations (
    household_id, category_id, budget_month, allocated_amount, currency
  ) VALUES
    (
      shared_household_id,
      (SELECT id FROM public.categories WHERE name = 'Groceries' AND household_id = shared_household_id),
      '2024-01-01', 500.00, 'EUR'
    ),
    (
      shared_household_id,
      (SELECT id FROM public.categories WHERE name = 'Dining Out' AND household_id = shared_household_id),
      '2024-01-01', 200.00, 'EUR'
    );
    -- ... more budget allocations ...

  GET DIAGNOSTICS imported_count = ROW_COUNT;
  RAISE NOTICE '  ✓ Imported % budget allocations', imported_count;

  -- ============================================================================
  -- Import Expenses
  -- ============================================================================
  RAISE NOTICE '  Importing expenses...';

  -- Expense INSERT statements generated from CSV
  INSERT INTO public.expenses (
    logged_by_user_id, household_id, category_id, account_id,
    amount, currency, converted_amount, converted_currency, exchange_rate,
    expense_date, description
  ) VALUES
    (
      user1_id, shared_household_id,
      (SELECT id FROM public.categories WHERE name = 'Groceries' AND household_id = shared_household_id),
      (SELECT id FROM public.accounts WHERE name = 'Checking Account' AND household_id = shared_household_id),
      50.00, 'EUR', 50.00, 'EUR', 1,
      '2024-01-15', 'Supermarket shopping'
    ),
    (
      user1_id, shared_household_id,
      (SELECT id FROM public.categories WHERE name = 'Dining Out' AND household_id = shared_household_id),
      (SELECT id FROM public.accounts WHERE name = 'Credit Card' AND household_id = shared_household_id),
      35.50, 'EUR', 35.50, 'EUR', 1,
      '2024-01-16', 'Restaurant dinner'
    );
    -- ... more expenses ...

  GET DIAGNOSTICS imported_count = ROW_COUNT;
  RAISE NOTICE '  ✓ Imported % expenses', imported_count;

  -- ============================================================================
  -- Summary
  -- ============================================================================
  RAISE NOTICE '========================================';
  RAISE NOTICE '[5/5] Data import complete!';
  RAISE NOTICE '========================================';
END $$;
