-- ============================================================================
-- 03_import_exchange_rates.sql - Import Exchange Rates
-- ============================================================================
-- Auto-generated by scripts/generate-exchange-rates.cjs
-- Do not edit manually - run `npm run seed:exchange-rates` to regenerate
-- Source: supabase/seeds/prod/raw/eur_brl_historical_rates.csv
--   (download from investing.com EUR/BRL historical data)
-- ============================================================================

DO $$
DECLARE
  imported_count INTEGER;
BEGIN
  RAISE NOTICE '========================================';
  RAISE NOTICE '[EXCHANGE RATES] Importing historical EUR/BRL exchange rates...';
  RAISE NOTICE '========================================';

  -- rate_to_eur = 1 / (EUR/BRL price)
  -- Example: EUR/BRL = 6.0990 → rate_to_eur = 0.163961
  INSERT INTO public.exchange_rates (currency, rate_date, rate_to_eur) VALUES
    ('BRL', '2026-02-20', 0.163961),
    ('BRL', '2026-02-19', 0.162983)
    -- ... more exchange rates generated from CSV ...
  ON CONFLICT (currency, rate_date) DO NOTHING;

  GET DIAGNOSTICS imported_count = ROW_COUNT;
  RAISE NOTICE '  ✓ Imported % exchange rates (skipped existing)', imported_count;

  RAISE NOTICE '========================================';
END $$;
