-- ============================================================================
-- 03_import_exchange_rates.sql - Import Exchange Rates
-- ============================================================================
-- Auto-generated by scripts/generate-exchange-rates.js
-- Do not edit manually - run `npm run seed:exchange-rates` to regenerate
-- ============================================================================

DO $$
DECLARE
  imported_count INTEGER;
BEGIN
  RAISE NOTICE '========================================';
  RAISE NOTICE '[EXCHANGE RATES] Importing historical exchange rates...';
  RAISE NOTICE '========================================';

  -- Exchange rate INSERT statements generated from expense data
  INSERT INTO public.exchange_rates (currency, rate_date, rate_to_eur) VALUES
    ('BRL', '2024-01-15', 0.17),
    ('BRL', '2024-01-16', 0.17);
    -- ... more exchange rates ...

  GET DIAGNOSTICS imported_count = ROW_COUNT;
  RAISE NOTICE '  ✓ Imported % exchange rates', imported_count;

  RAISE NOTICE '========================================';
END $$;
