-- ============================================================================
-- CATEGORIES SEED (DEPRECATED)
-- ============================================================================
-- Categories are now household-scoped and automatically seeded when a new
-- household is created via the handle_new_user() trigger.
--
-- For existing households created by 02_users_and_accounts.sql, categories
-- are seeded there directly.
--
-- This file is kept for reference but does nothing.
-- ============================================================================
